// Code generated by mockery (manual). DO NOT EDIT.

package mocks

import (
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"github.com/lapakgaming/i18n-center/models"
)

// MockAuditServicer is an autogenerated mock type for the AuditServicer interface.
type MockAuditServicer struct {
	mock.Mock
}

// LogCreate provides a mock function with given fields: userID, username, resourceType, resourceID, resourceCode, data, ipAddress, userAgent
func (_m *MockAuditServicer) LogCreate(userID uuid.UUID, username string, resourceType string, resourceID uuid.UUID, resourceCode string, data interface{}, ipAddress string, userAgent string) error {
	ret := _m.Called(userID, username, resourceType, resourceID, resourceCode, data, ipAddress, userAgent)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, uuid.UUID, string, interface{}, string, string) error); ok {
		r0 = rf(userID, username, resourceType, resourceID, resourceCode, data, ipAddress, userAgent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogUpdate provides a mock function with given fields: userID, username, resourceType, resourceID, resourceCode, before, after, ipAddress, userAgent
func (_m *MockAuditServicer) LogUpdate(userID uuid.UUID, username string, resourceType string, resourceID uuid.UUID, resourceCode string, before interface{}, after interface{}, ipAddress string, userAgent string) error {
	ret := _m.Called(userID, username, resourceType, resourceID, resourceCode, before, after, ipAddress, userAgent)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, uuid.UUID, string, interface{}, interface{}, string, string) error); ok {
		r0 = rf(userID, username, resourceType, resourceID, resourceCode, before, after, ipAddress, userAgent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogDelete provides a mock function with given fields: userID, username, resourceType, resourceID, resourceCode, data, ipAddress, userAgent
func (_m *MockAuditServicer) LogDelete(userID uuid.UUID, username string, resourceType string, resourceID uuid.UUID, resourceCode string, data interface{}, ipAddress string, userAgent string) error {
	ret := _m.Called(userID, username, resourceType, resourceID, resourceCode, data, ipAddress, userAgent)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, uuid.UUID, string, interface{}, string, string) error); ok {
		r0 = rf(userID, username, resourceType, resourceID, resourceCode, data, ipAddress, userAgent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogAction provides a mock function with given fields: userID, username, action, resourceType, resourceID, resourceCode, changes, ipAddress, userAgent
func (_m *MockAuditServicer) LogAction(userID uuid.UUID, username string, action string, resourceType string, resourceID uuid.UUID, resourceCode string, changes map[string]interface{}, ipAddress string, userAgent string) error {
	ret := _m.Called(userID, username, action, resourceType, resourceID, resourceCode, changes, ipAddress, userAgent)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, string, uuid.UUID, string, map[string]interface{}, string, string) error); ok {
		r0 = rf(userID, username, action, resourceType, resourceID, resourceCode, changes, ipAddress, userAgent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAuditLogs provides a mock function with given fields: resourceType, resourceID, limit
func (_m *MockAuditServicer) GetAuditLogs(resourceType string, resourceID uuid.UUID, limit int) ([]models.AuditLog, error) {
	ret := _m.Called(resourceType, resourceID, limit)

	var r0 []models.AuditLog
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, int) []models.AuditLog); ok {
		r0 = rf(resourceType, resourceID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AuditLog)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, uuid.UUID, int) error); ok {
		r1 = rf(resourceType, resourceID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuditLogsByUser provides a mock function with given fields: userID, limit
func (_m *MockAuditServicer) GetAuditLogsByUser(userID uuid.UUID, limit int) ([]models.AuditLog, error) {
	ret := _m.Called(userID, limit)

	var r0 []models.AuditLog
	if rf, ok := ret.Get(0).(func(uuid.UUID, int) []models.AuditLog); ok {
		r0 = rf(userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AuditLog)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID, int) error); ok {
		r1 = rf(userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChangesForResource provides a mock function with given fields: resourceType, resourceID
func (_m *MockAuditServicer) GetChangesForResource(resourceType string, resourceID uuid.UUID) ([]models.AuditLog, error) {
	ret := _m.Called(resourceType, resourceID)

	var r0 []models.AuditLog
	if rf, ok := ret.Get(0).(func(string, uuid.UUID) []models.AuditLog); ok {
		r0 = rf(resourceType, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AuditLog)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, uuid.UUID) error); ok {
		r1 = rf(resourceType, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAuditServicer creates a new instance of MockAuditServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAuditServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditServicer {
	mock := &MockAuditServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
